//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.default_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.default_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabPinch
        {
            get
            {
                return SteamVR_Actions.default_GrabPinch;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabGrip
        {
            get
            {
                return SteamVR_Actions.default_GrabGrip;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Move
        {
            get
            {
                return SteamVR_Actions.default_Move;
            }
        }
        
        public virtual SteamVR_Action_Boolean SmoothLeft
        {
            get
            {
                return SteamVR_Actions.default_SmoothLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean SmoothRight
        {
            get
            {
                return SteamVR_Actions.default_SmoothRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean Thrust
        {
            get
            {
                return SteamVR_Actions.default_Thrust;
            }
        }
        
        public virtual SteamVR_Action_Boolean Jump
        {
            get
            {
                return SteamVR_Actions.default_Jump;
            }
        }
        
        public virtual SteamVR_Action_Boolean Break
        {
            get
            {
                return SteamVR_Actions.default_Break;
            }
        }
        
        public virtual SteamVR_Action_Boolean Boost
        {
            get
            {
                return SteamVR_Actions.default_Boost;
            }
        }
        
        public virtual SteamVR_Action_Boolean PitchUp
        {
            get
            {
                return SteamVR_Actions.default_PitchUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean Pitch_Down
        {
            get
            {
                return SteamVR_Actions.default_Pitch_Down;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.default_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
